USE fitcare;

CREATE TABLE fitcare.PROVINCIAS (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_PROVICIAS PRIMARY KEY,
	Nombre VARCHAR (100) NOT NULL,
	Estado BIT NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Provincias_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.PROVINCIAS;
