ALTER TABLE dbo.AspNetUsers
    ADD IdProvincia UNIQUEIDENTIFIER NULL CONSTRAINT FK_Usuarios_Provincias
    FOREIGN KEY REFERENCES fitcare.PROVINCIAS (Id) ON DELETE CASCADE;

ALTER TABLE dbo.AspNetUsers
    ADD IdCanton UNIQUEIDENTIFIER NULL CONSTRAINT FK_Usuarios_Cantones
    FOREIGN KEY REFERENCES fitcare.CANTONES (Id) ON DELETE CASCADE;

ALTER TABLE dbo.AspNetUsers
    ADD IdDistrito UNIQUEIDENTIFIER NULL CONSTRAINT FK_Usuarios_Distritos
    FOREIGN KEY REFERENCES fitcare.DISTRITOS (Id) ON DELETE CASCADE;

ALTER TABLE dbo.AspNetUsers ADD URLFotografia VARCHAR(1000) NULL;

ALTER TABLE dbo.AspNetUsers ADD FechaIngresoInscripcion DATETIME NULL;

ALTER TABLE dbo.AspNetUsers ADD FechaRenovacion DATETIME NULL;

ALTER TABLE dbo.AspNetUsers ADD DateCreated DATETIME NOT NULL CONSTRAINT DF_Usuarios_DateCreated DEFAULT GETUTCDATE();

ALTER TABLE dbo.AspNetUsers ADD CreatedBy NVARCHAR(100) NOT NULL;

ALTER TABLE dbo.AspNetUsers ADD DateUpdated DATETIME NULL;

ALTER TABLE dbo.AspNetUsers ADD UpdatedBy NVARCHAR(100) NULL;

SELECT * FROM AspNetUsers;
