USE fitcare;

CREATE TABLE fitcare.CANTONES (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CANTONES PRIMARY KEY,
	Id_Provincia UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CANTONES_PROVINCIAS FOREIGN KEY REFERENCES fitcare.PROVINCIAS (Id),
	Nombre VARCHAR (150) NOT NULL,
	Estado BIT NOT NULL,
	Id_Canton_INEC INT NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Cantones_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.CANTONES;
