USE fitcare;

CREATE TABLE fitcare.Cantones (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Cantones PRIMARY KEY,
	IdProvincia UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Cantones_Provincias FOREIGN KEY REFERENCES fitcare.Provincias (Id) ON DELETE CASCADE,
	Nombre VARCHAR (150) NOT NULL,
	Estado BIT NOT NULL,
	IdINEC INT NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Cantones_DateCreated DEFAULT GETUTCDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.Cantones;
