USE fitcare;

CREATE TABLE fitcare.TIPOS_MAQUINA (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TIPOS_MAQUINA PRIMARY KEY ,
    Nombre VARCHAR(255) NOT NULL,
    Codigo VARCHAR(20) NOT NULL CONSTRAINT UQ_TiposMaquina_Codigo UNIQUE,
    Estado BIT NOT NULL,
    DateCreated DATETIME NOT NULL CONSTRAINT DF_TiposMaquina_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.TIPOS_MAQUINA;
