USE fitcare;

CREATE TABLE fitcare.MAQUINAS (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_MAQUINAS PRIMARY KEY,
	Id_Tipo_Maquina UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_MAQUINAS_TIPOS_MAQUINA FOREIGN KEY REFERENCES fitcare.TIPOS_MAQUINA (Id),
	Codigo VARCHAR(100) NOT NULL CONSTRAINT UQ_Maquinas_Codigo UNIQUE,
	NumeroActivo VARCHAR (100) NOT NULL,
	Nombre VARCHAR (255) NOT NULL,
	Estado BIT NOT NULL,
	FechaAdquisicion DATETIME NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Maquinas_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.MAQUINAS;
