USE fitcare;

CREATE TABLE fitcare.Distritos (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Distritos PRIMARY KEY,
	IdCanton UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Distritos_Cantones FOREIGN KEY REFERENCES fitcare.Cantones (Id) ON DELETE CASCADE,
    Nombre VARCHAR (100) NOT NULL,
    Estado BIT NOT NULL,
    IdINEC INT NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Distritos_DateCreated DEFAULT GETUTCDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.Distritos;
