USE fitcare;

CREATE TABLE fitcare.TiposMaquina (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TiposMaquina PRIMARY KEY ,
    Nombre VARCHAR(255) NOT NULL,
    Codigo VARCHAR(20) NOT NULL CONSTRAINT UQ_TiposMaquina_Codigo UNIQUE,
    Estado BIT NOT NULL,
    DateCreated DATETIME NOT NULL CONSTRAINT DF_TiposMaquina_DateCreated DEFAULT GETUTCDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.TiposMaquina;
