USE fitcare;

CREATE TABLE fitcare.Maquinas (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Maquinas PRIMARY KEY,
	IdTipoMaquina UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Maquinas_TiposMaquina FOREIGN KEY REFERENCES fitcare.TiposMaquina (Id) ON DELETE CASCADE,
	Codigo VARCHAR(100) NOT NULL CONSTRAINT UQ_Maquinas_Codigo UNIQUE,
	NumeroActivo VARCHAR (100) NOT NULL,
	Nombre VARCHAR (255) NOT NULL,
	Estado BIT NOT NULL,
	FechaAdquisicion DATETIME NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Maquinas_DateCreated DEFAULT GETUTCDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.Maquinas;
