USE fitcare;

CREATE TABLE fitcare.TIPOS_MEDIDA (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TIPOS_MEDIDA PRIMARY KEY,
	Codigo VARCHAR(100) NOT NULL CONSTRAINT UQ_TIPOS_MEDIDA_CODIGO UNIQUE,
	Nombre VARCHAR (255) NOT NULL,
	Estado BIT NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_TiposMedida_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.TIPOS_MEDIDA;
