USE fitcare;

CREATE TABLE fitcare.EJERCICIOS (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_EJERCICIOS PRIMARY KEY,
	Id_Tipo_Ejercicio UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_EJERCICIOS_TIPOS_EJERCICIO FOREIGN KEY REFERENCES fitcare.TIPOS_EJERCICIO (Id),
	Codigo VARCHAR (100) NOT NULL CONSTRAINT UQ_Ejercicios_Codigo UNIQUE,
	Nombre VARCHAR (255) NOT NULL,
	Estado BIT NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Ejercicios_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.EJERCICIOS;
