USE fitcare;

CREATE TABLE fitcare.INSTRUCTORES (
	IdUsuario UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_INSTRUCTORES PRIMARY KEY,
	IdProvincia UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_INSTRUCTORES_PROVINCIAS FOREIGN KEY REFERENCES fitcare.PROVINCIAS (Id),
	IdCanton UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_INSTRUCTORES_CANTONES FOREIGN KEY REFERENCES fitcare.CANTONES (Id),
	IdDistrito UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_INSTRUCTORES_DISTRITOS FOREIGN KEY REFERENCES fitcare.DISTRITOS (Id),
	FechaIngreso DATETIME NOT NULL,
	Fotografia VARCHAR(1000) NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Instructores_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
	--CONSTRAINT PK_INSTRUCTORES_USUARIOS FOREIGN KEY (IdUsuario) REFERENCES AspNetUsers (Id),
);

SELECT * FROM AspNetUsers;
SELECT * FROM fitcare.INSTRUCTORES;
