USE fitcare;

CREATE TABLE fitcare.Ejercicios (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Ejercicios PRIMARY KEY,
	IdTipoEjercicio UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_EJercicios_TiposEjercicio FOREIGN KEY REFERENCES fitcare.TiposEjercicio (Id) ON DELETE CASCADE,
	Codigo VARCHAR (100) NOT NULL CONSTRAINT UQ_Ejercicios_Codigo UNIQUE,
	Nombre VARCHAR (255) NOT NULL,
	Estado BIT NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Ejercicios_DateCreated DEFAULT GETUTCDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.Ejercicios;
