ALTER TABLE dbo.AspNetUsers ADD IdProvincia UNIQUEIDENTIFIER NULL CONSTRAINT FK_USUARIOS_PROVINCIAS FOREIGN KEY REFERENCES fitcare.PROVINCIAS (Id);
ALTER TABLE dbo.AspNetUsers ADD IdCanton UNIQUEIDENTIFIER NULL CONSTRAINT FK_USUARIOS_CANTONES FOREIGN KEY REFERENCES fitcare.CANTONES (Id);
ALTER TABLE dbo.AspNetUsers ADD IdDistrito UNIQUEIDENTIFIER NULL CONSTRAINT FK_USUARIOS_DISTRITOS FOREIGN KEY REFERENCES fitcare.DISTRITOS (Id);
ALTER TABLE dbo.AspNetUsers ADD URLFotografia VARCHAR(1000) NULL;
ALTER TABLE dbo.AspNetUsers ADD FechaIngreso DATETIME NULL;

-- DateCreated DATETIME NOT NULL CONSTRAINT DF_Instructores_DateCreated DEFAULT GETDATE(),
-- CreatedBy NVARCHAR(100) NOT NULL,
-- DateUpdated DATETIME NULL,
-- UpdatedBy NVARCHAR(100) NULL

SELECT * FROM AspNetUsers;
