USE fitcare;

CREATE TABLE fitcare.CLIENTES (
	IdUsuario  NVARCHAR (450) NOT NULL CONSTRAINT PK_CLIENTES PRIMARY KEY,
	IdProvincia UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CLIENTES_PROVINCIAS FOREIGN KEY REFERENCES fitcare.PROVINCIAS (Id),
	IdCanton UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CLIENTES_CANTONES FOREIGN KEY REFERENCES fitcare.CANTONES (Id),
	IdDistrito UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CLIENTES_DISTRITOS FOREIGN KEY REFERENCES fitcare.DISTRITOS (Id),
	FechaInscripcion DATETIME NOT NULL,
	FechaRenovacion DATETIME NOT NULL,
	Fotografia VARCHAR(1000) NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_Clientes_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
	--CONSTRAINT FK_CLIENTES_USUARIOS FOREIGN KEY (IdUsuario) REFERENCES AspNetUsers (Id),	
);

SELECT * FROM fitcare.CLIENTES;
