USE fitcare;

CREATE TABLE fitcare.DETALLE_RUTINA (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DETALLE_RUTINA PRIMARY KEY,
    IdRutina UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_DETALLE_RUTINAS_RUTINAS FOREIGN KEY REFERENCES fitcare.RUTINAS (Id),
    IdEjercicio UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_DETALLE_RUTINAS_EJERCICIOS FOREIGN KEY REFERENCES fitcare.EJERCICIOS (Id),
    IdMaquina UNIQUEIDENTIFIER NULL CONSTRAINT FK_DETALLE_RUTINA_MAQUINA FOREIGN KEY REFERENCES fitcare.MAQUINAS (Id),
	Num_Series INT NOT NULL,
	Num_Repeticiones INT NOT NULL,
    Minutos_Descanso INT NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_DetalleRutina_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.DETALLE_RUTINA;
