USE fitcare;

CREATE TABLE fitcare.TiposMedida (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TiposMedida PRIMARY KEY,
	Codigo VARCHAR(100) NOT NULL CONSTRAINT UQ_TiposMedida_Codigo UNIQUE,
	Nombre VARCHAR (255) NOT NULL,
	Estado BIT NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_TiposMedida_DateCreated DEFAULT GETUTCDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.TiposMedida;
