USE fitcare;

CREATE TABLE fitcare.GRUPOS_MUSCULARES (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_GRUPOS_MUSCULARES PRIMARY KEY,
	Nombre VARCHAR (255) NOT NULL,
    Descripcion VARCHAR (4000) NOT NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_GruposMusculares_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.GRUPOS_MUSCULARES;
