USE fitcare;

CREATE TABLE fitcare.DETALLE_MEDIDAS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DETALLE_MEDIDAS PRIMARY KEY,
    IdRutina UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_DETALLE_MEDIDAS_RUTINAS FOREIGN KEY REFERENCES fitcare.RUTINAS (Id),
    IdTipoMedida UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_DETALLE_MEDIDAS_TIPOS_MEDIDA FOREIGN KEY REFERENCES fitcare.TIPOS_MEDIDA (Id),
    ValorMedida VARCHAR (50) NOT NULL,
    Comentario VARCHAR(4000) NULL,
	DateCreated DATETIME NOT NULL CONSTRAINT DF_DetalleMedidas_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.DETALLE_MEDIDAS;
