USE fitcare;

CREATE TABLE fitcare.GRUPOS_MUSCULARES_EJERCICIO (
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_GRUPOS_MUSCULARES_EJERCICIO PRIMARY KEY,
	Id_Ejercicio UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_GRUPOS_MUSCULARES_EJERCICIO_EJERCICIOS FOREIGN KEY REFERENCES fitcare.EJERCICIOS (Id),
    Id_Grupo_Muscular UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_GRUPOS_MUSCULARES_EJERCICIO_GRUPOS_MUSCULARES FOREIGN KEY REFERENCES fitcare.GRUPOS_MUSCULARES (Id),
	DateCreated DATETIME NOT NULL CONSTRAINT DF_GruposMuscularesEjercicio_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.GRUPOS_MUSCULARES_EJERCICIO;
