USE fitcare;

CREATE TABLE fitcare.DETALLE_GRUPOS_MUSCULARES (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DETALLE_GRUPOS_MUSCULARES PRIMARY KEY,
    IdRutina UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_DETALLE_GRUPOS_MUSCULARES_RUTINAS FOREIGN KEY REFERENCES fitcare.RUTINAS (Id),
    IdGrupoMuscular UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_DETALLE_GRUPOS_MUSCULARES_GRUPOS_MUSCULARES FOREIGN KEY REFERENCES fitcare.GRUPOS_MUSCULARES (Id),
	DateCreated DATETIME NOT NULL CONSTRAINT DF_DetalleGruposMusculares_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL
);

SELECT * FROM fitcare.DETALLE_GRUPOS_MUSCULARES;
