USE fitcare;

CREATE TABLE fitcare.NOVEDADES (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_NOVEDADES PRIMARY KEY,
    Fecha DATETIME NOT NULL,
    Titulo VARCHAR(255) NOT NULL,
	Descripcion VARCHAR(4000) NOT NULL,
    Vigente BIT NOT NULL,
);

SELECT * FROM fitcare.NOVEDADES;
