USE [Gimnacio]
GO
/****** Object:  StoredProcedure [dbo].[ELIMINAR_CLIENTES]    Script Date: 4/2/2019 00:45:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ELIMINAR_INSTRUCTOR]
    @ID_INSTRUCTOR INT
AS
BEGIN
    DELETE Instructores WHERE id_Instructor=@ID_INSTRUCTOR
END

CREATE PROCEDURE dbo.ELIMINAR_INSTRUCTOR
    @ID_INSTRUCTOR INT
AS
BEGIN
    DELETE Instructores WHERE id_Instructor=@ID_INSTRUCTOR
END
