USE [Gimnacio]
GO
/****** Object:  StoredProcedure [dbo].[ELIMINAR_JUGADOR]    Script Date: 6/2/2019 23:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ELIMINAR_JUGADOR]
    @ID_JUGADOR INT
AS
BEGIN
    DELETE Jugadores WHERE id_Jugador=@ID_JUGADOR
END

CREATE PROCEDURE dbo.ELIMINAR_JUGADOR
    @ID_JUGADOR INT
AS
BEGIN
    DELETE Jugadores WHERE id_Jugador=@ID_JUGADOR
END
