USE [Gimnacio]
GO
/****** Object:  StoredProcedure [dbo].[INSERTA_USUARIO]    Script Date: 12/2/2019 23:44:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INSERTA_USUARIO]

@CORREO VARCHAR(150),
@CONTRASE�A VARCHAR
(100),
@CEDULA VARCHAR
(100),
@NOMBRE VARCHAR
(150),
@PRIMER_APELLIDO VARCHAR
(150),
@SEGUNDO_APELLIDO VARCHAR
(150),
@TIPO_USUARIO VARCHAR
(225)

AS
BEGIN
    INSERT INTO Usuarios
    VALUES(@CORREO, @CONTRASE
    �A,@CEDULA,@NOMBRE,@PRIMER_APELLIDO,@SEGUNDO_APELLIDO,@TIPO_USUARIO)
END

CREATE PROCEDURE [dbo].[PA_INSERTAR_USUARIO]

    @NOMBRE VARCHAR(255),
    @APELLIDO1 VARCHAR(255),
    @APELLIDO2 VARCHAR(255),
    @NUMERODEIDENTIFICACION VARCHAR(255),
    @FOTOGRAFIA IMAGE,
    @CORREOELECTRONICO VARCHAR(255),
    @CONTRASEÑA VARCHAR(255),
    @FK_PROVINCIA INT ,
    @FK_CANTON INT,
    @FK_DISTRITO INT,
    @FK_TIPO_USUARIO INT

AS
BEGIN

    INSERT INTO USUARIOS
    VALUES(@NOMBRE, @APELLIDO1, @APELLIDO2, @NUMERODEIDENTIFICACION, @FOTOGRAFIA,
            @CORREOELECTRONICO, @CONTRASEÑA, @FK_PROVINCIA, @FK_CANTON, @FK_DISTRITO, @FK_TIPO_USUARIO)

END

CREATE PROCEDURE dbo.INSERTA_USUARIO

    @CORREO VARCHAR(150),
    @CONTRASEÑA VARCHAR(100),
    @CEDULA VARCHAR(100),
    @NOMBRE VARCHAR(150),
    @PRIMER_APELLIDO VARCHAR(150),
    @SEGUNDO_APELLIDO VARCHAR(150),
    @TIPO_USUARIO VARCHAR(225)

AS
BEGIN
    INSERT INTO Usuarios
    VALUES(@CORREO, @CONTRASEÑA, @CEDULA, @NOMBRE, @PRIMER_APELLIDO, @SEGUNDO_APELLIDO, @TIPO_USUARIO)
END
