

CREATE PROCEDURE [dbo].[PA_ACTUALIZAR_RUTINAS]
    @ID_RUTINA INT,
    @FECHA_INICIO_RUTINA VARCHAR (255),
    @FECHA_FIN_RUTINA VARCHAR (255),
    @OBJETIVOS VARCHAR(800),
    @NUMERO_DE_REPETICIONES VARCHAR(255),
    @NUMERO_DE_DESCANSOS VARCHAR(255),
    @CUELLO VARCHAR(255),
    @HOMBRO VARCHAR(255),
    @PECHO VARCHAR(255),
    @ESPALDA VARCHAR(255),
    @ABDOMEN VARCHAR(255),
    @ANTEBRAZOS VARCHAR(255),
    @PIERNA VARCHAR(255),
    @PANTORRILLAS VARCHAR(255),
    @BICEPS VARCHAR(255),
    @TRICEPS VARCHAR(255),
    @OBLICUOS VARCHAR(255),
    @FK_TIPO_MAQUINA INT,
    @FK_TIPO_EJERCICIO INT,
    @FK_USUARIO_INSTRUCTOR INT,
    @FK_USUARIO_JUGADOR INT


AS
BEGIN

    UPDATE NUEVARUTINA SET FECHA_INICIO_RUTINA=@FECHA_INICIO_RUTINA,FECHA_FIN_RUTINA=@FECHA_FIN_RUTINA,
Objetivos=@OBJETIVOS,Numero_de_Repeticiones=@NUMERO_DE_REPETICIONES,Cuello=@CUELLO,
Hombros=@HOMBRO,Pecho=@PECHO,Espalda=@ESPALDA,Abdomen=@ABDOMEN,Antebrazos=@ANTEBRAZOS,Pierna=@PIERNA,
PANTORRILLAS=@PANTORRILLAS, BICEPS=@BICEPS,Triceps=@TRICEPS,Oblicuos=@OBLICUOS,FK_TIPO_MAQUINA=@FK_TIPO_MAQUINA,FK_TIPO_EJERCICIO=@FK_TIPO_EJERCICIO,
FK_USUARIO_INSTRUCTOR=@FK_USUARIO_INSTRUCTOR,FK_USUARIO_JUGADOR=@FK_USUARIO_JUGADOR
WHERE ID_RUTINA=@ID_RUTINA
END

CREATE PROCEDURE [dbo].[PA_ACTUALIZAR_RUTINAS]
    @ID_RUTINA INT,
    @FECHA_INICIO_RUTINA VARCHAR (255),
    @FECHA_FIN_RUTINA VARCHAR (255),
    @OBJETIVOS VARCHAR(800),
    @NUMERO_DE_REPETICIONES VARCHAR(255),
    @NUMERO_DE_DESCANSOS VARCHAR(255),
    @CUELLO VARCHAR(255),
    @HOMBRO VARCHAR(255),
    @PECHO VARCHAR(255),
    @ESPALDA VARCHAR(255),
    @ABDOMEN VARCHAR(255),
    @ANTEBRAZOS VARCHAR(255),
    @PIERNA VARCHAR(255),
    @PANTORRILLAS VARCHAR(255),
    @BICEPS VARCHAR(255),
    @TRICEPS VARCHAR(255),
    @OBLICUOS VARCHAR(255),
    @FK_TIPO_MAQUINA INT,
    @FK_TIPO_EJERCICIO INT,
    @FK_USUARIO_INSTRUCTOR INT,
    @FK_USUARIO_JUGADOR INT


AS
BEGIN

    UPDATE NUEVARUTINA SET FECHA_INICIO_RUTINA=@FECHA_INICIO_RUTINA,FECHA_FIN_RUTINA=@FECHA_FIN_RUTINA,
Objetivos=@OBJETIVOS,Numero_de_Repeticiones=@NUMERO_DE_REPETICIONES,Cuello=@CUELLO,
Hombros=@HOMBRO,Pecho=@PECHO,Espalda=@ESPALDA,Abdomen=@ABDOMEN,Antebrazos=@ANTEBRAZOS,Pierna=@PIERNA,
PANTORRILLAS=@PANTORRILLAS, BICEPS=@BICEPS,Triceps=@TRICEPS,Oblicuos=@OBLICUOS,FK_TIPO_MAQUINA=@FK_TIPO_MAQUINA,FK_TIPO_EJERCICIO=@FK_TIPO_EJERCICIO,
FK_USUARIO_INSTRUCTOR=@FK_USUARIO_INSTRUCTOR,FK_USUARIO_JUGADOR=@FK_USUARIO_JUGADOR
WHERE ID_RUTINA=@ID_RUTINA
END
