
CREATE PROCEDURE PA_ACTUALIZAR_PROVINCIA

    @ID_PROVINCIA INT,
    @NOMBRE VARCHAR(100),
    @USUARIO_CREA VARCHAR(50),
    @FECHA_CREA DATETIME,
    @USUARIO_MODIFICA VARCHAR(50),
    @FECHA_MODIFICA DATETIME,
    @VC_ESTADO VARCHAR(3)

AS
BEGIN

    UPDATE PROVINCIA SET nombre=@NOMBRE,usuario_Crea=@USUARIO_CREA,fecha_Crea=@FECHA_CREA,
usuario_Modifica=@USUARIO_MODIFICA,fecha_Modifica=@FECHA_MODIFICA,vc_Estado=@VC_ESTADO WHERE id_Provincia=@ID_PROVINCIA

END

CREATE PROCEDURE [dbo].[PA_ACTUALIZAR_PROVINCIA]

    @ID_PROVINCIA INT,
    @NOMBRE VARCHAR(100),
    @USUARIO_CREA VARCHAR(50),
    @FECHA_CREA DATETIME,
    @USUARIO_MODIFICA VARCHAR(50),
    @FECHA_MODIFICA DATETIME,
    @VC_ESTADO VARCHAR(3)

AS
BEGIN

    UPDATE PROVINCIA SET nombre=@NOMBRE,usuario_Crea=@USUARIO_CREA,fecha_Crea=@FECHA_CREA,
usuario_Modifica=@USUARIO_MODIFICA,fecha_Modifica=@FECHA_MODIFICA,vc_Estado=@VC_ESTADO WHERE id_Provincia=@ID_PROVINCIA

END

CREATE PROCEDURE dbo.PA_ACTUALIZAR_PROVINCIA

    @ID_PROVINCIA INT,
    @NOMBRE VARCHAR(100),
    @USUARIO_CREA VARCHAR(50),
    @FECHA_CREA DATETIME,
    @USUARIO_MODIFICA VARCHAR(50),
    @FECHA_MODIFICA DATETIME,
    @VC_ESTADO VARCHAR(3)

AS
BEGIN

    UPDATE PROVINCIA SET nombre=@NOMBRE,usuario_Crea=@USUARIO_CREA,fecha_Crea=@FECHA_CREA,
usuario_Modifica=@USUARIO_MODIFICA,fecha_Modifica=@FECHA_MODIFICA,vc_Estado=@VC_ESTADO WHERE id_Provincia=@ID_PROVINCIA
