

create procedure [dbo].[PA_ACTUALIZAR_TIPO_USUARIO]
	@ID_TIPO_USUARIO INT,
	@TIPO_USUARIO VARCHAR(255)

AS
BEGIN
	UPDATE  TIPO_USUARIO SET TIPO_USUARIO=@TIPO_USUARIO WHERE ID_TIPO_USUARIO=@ID_TIPO_USUARIO
END

create procedure [dbo].[PA_ACTUALIZAR_TIPO_USUARIO]
	@ID_TIPO_USUARIO INT,
	@TIPO_USUARIO VARCHAR(255)

AS
BEGIN
	UPDATE  TIPO_USUARIO SET TIPO_USUARIO=@TIPO_USUARIO WHERE ID_TIPO_USUARIO=@ID_TIPO_USUARIO
END

create procedure dbo.PA_ACTUALIZAR_TIPO_USUARIO
	@ID_TIPO_USUARIO INT,
	@TIPO_USUARIO VARCHAR(255)

AS
BEGIN
	UPDATE  TIPO_USUARIO SET TIPO_USUARIO=@TIPO_USUARIO WHERE ID_TIPO_USUARIO=@ID_TIPO_USUARIO
END
