CREATE PROCEDURE PA_ACTUALIZAR_USUARIO

@ID_USUARIO INT,
@NOMBRE VARCHAR(255),
@APELLIDO1 VARCHAR(255),
@APELLIDO2 VARCHAR(255),
@NUMERODEIDENTIFICACION VARCHAR(255),
@FOTOGRAFIA IMAGE,
@CORREOELECTRONICO VARCHAR(255),
@CONTRASE�A VARCHAR
(255)

AS
BEGIN

    UPDATE USUARIOS SET Nombre=@NOMBRE,PrimerApellido=@APELLIDO1,SegundoApellido=@APELLIDO2,NumerodeIndentificacion=@NUMERODEIDENTIFICACION,
Fotografia=@FOTOGRAFIA,CorreoElectronico=@CORREOELECTRONICO,Contrase�a=@CONTRASE�A WHERE id_Usuario=@ID_USUARIO

END

CREATE PROCEDURE [dbo].[PA_ACTUALIZAR_USUARIO]

    @ID_USUARIO INT,
    @NOMBRE VARCHAR(255),
    @APELLIDO1 VARCHAR(255),
    @APELLIDO2 VARCHAR(255),
    @NUMERODEIDENTIFICACION VARCHAR(255),
    @FOTOGRAFIA IMAGE,
    @CORREOELECTRONICO VARCHAR(255),
    @CONTRASEÑA VARCHAR(255)

AS
BEGIN

    UPDATE USUARIOS SET Nombre=@NOMBRE,PrimerApellido=@APELLIDO1,SegundoApellido=@APELLIDO2,NumerodeIndentificacion=@NUMERODEIDENTIFICACION,
Fotografia=@FOTOGRAFIA,CorreoElectronico=@CORREOELECTRONICO,Contraseña=@CONTRASEÑA WHERE id_Usuario=@ID_USUARIO

END

CREATE PROCEDURE dbo.PA_ACTUALIZAR_USUARIO

    @ID_USUARIO INT,
    @NOMBRE VARCHAR(255),
    @APELLIDO1 VARCHAR(255),
    @APELLIDO2 VARCHAR(255),
    @NUMERODEIDENTIFICACION VARCHAR(255),
    @FOTOGRAFIA IMAGE,
    @CORREOELECTRONICO VARCHAR(255),
    @CONTRASEÑA VARCHAR(255)

AS
BEGIN

    UPDATE USUARIOS SET Nombre=@NOMBRE,PrimerApellido=@APELLIDO1,SegundoApellido=@APELLIDO2,NumerodeIndentificacion=@NUMERODEIDENTIFICACION,
Fotografia=@FOTOGRAFIA,CorreoElectronico=@CORREOELECTRONICO,Contraseña=@CONTRASEÑA WHERE id_Usuario=@ID_USUARIO

END
