
CREATE PROCEDURE PA_ACTUALIZAR_CANTON

    @ID_CANTON INT,
    @ID_PROVINCIA INT,
    @NOMBRE VARCHAR(100),
    @USUARIO_CREA VARCHAR(50),
    @FECHA_CREACION DATETIME,
    @USUARIO_MODIFICACION VARCHAR(50),
    @FECHA_MODIFICACION DATETIME,
    @VC_ESTADO VARCHAR(3),
    @ID_CANTONINEC INT

AS
BEGIN

    UPDATE CANTON SET id_Provincia=@ID_PROVINCIA,nombre=@NOMBRE,
usuario_crea=@USUARIO_CREA,fecha_creacion=@FECHA_CREACION,usuario_modifcacion=@USUARIO_MODIFICACION,
fecha_modificacion=@FECHA_MODIFICACION,vc_Estado=@VC_ESTADO where id_Canton=@ID_CANTON

END

CREATE PROCEDURE [dbo].[PA_ACTUALIZAR_CANTON]

    @ID_CANTON INT,
    @ID_PROVINCIA INT,
    @NOMBRE VARCHAR(100),
    @USUARIO_CREA VARCHAR(50),
    @FECHA_CREACION DATETIME,
    @USUARIO_MODIFICACION VARCHAR(50),
    @FECHA_MODIFICACION DATETIME,
    @VC_ESTADO VARCHAR(3),
    @ID_CANTONINEC INT

AS
BEGIN

    UPDATE CANTON SET id_Provincia=@ID_PROVINCIA,nombre=@NOMBRE,
usuario_crea=@USUARIO_CREA,fecha_creacion=@FECHA_CREACION,usuario_modifcacion=@USUARIO_MODIFICACION,
fecha_modificacion=@FECHA_MODIFICACION,vc_Estado=@VC_ESTADO where id_Canton=@ID_CANTON

END

CREATE PROCEDURE dbo.PA_ACTUALIZAR_CANTON

    @ID_CANTON INT,
    @ID_PROVINCIA INT,
    @NOMBRE VARCHAR(100),
    @USUARIO_CREA VARCHAR(50),
    @FECHA_CREACION DATETIME,
    @USUARIO_MODIFICACION VARCHAR(50),
    @FECHA_MODIFICACION DATETIME,
    @VC_ESTADO VARCHAR(3),
    @ID_CANTONINEC INT

AS
BEGIN

    UPDATE CANTON SET id_Provincia=@ID_PROVINCIA,nombre=@NOMBRE,
usuario_crea=@USUARIO_CREA,fecha_creacion=@FECHA_CREACION,usuario_modifcacion=@USUARIO_MODIFICACION,
fecha_modificacion=@FECHA_MODIFICACION,vc_Estado=@VC_ESTADO where id_Canton=@ID_CANTON

END
