
create procedure [dbo].[PA_ELIMINAR_USUARIO]
	@ID_USUARIO INT
AS
BEGIN
	DELETE USUARIOS WHERE id_Usuario=@ID_USUARIO
END

create procedure [dbo].[PA_ELIMINAR_USUARIO]
	@ID_USUARIO INT
AS
BEGIN
	DELETE USUARIOS WHERE id_Usuario=@ID_USUARIO
END

create procedure dbo.PA_ELIMINAR_USUARIO
	@ID_USUARIO INT
AS
BEGIN
	DELETE USUARIOS WHERE id_Usuario=@ID_USUARIO
END
