CREATE procedure [dbo].[PA_ELIMINAR_CANTON]
	@ID_CANTON INT
AS
BEGIN
	DELETE CANTON WHERE id_Canton=@ID_CANTON
END

CREATE procedure [dbo].[PA_ELIMINAR_CANTON]
	@ID_CANTON INT
AS
BEGIN
	DELETE CANTON WHERE id_Canton=@ID_CANTON
END

CREATE procedure dbo.PA_ELIMINAR_CANTON
	@ID_CANTON INT
AS
BEGIN
	DELETE CANTON WHERE id_Canton=@ID_CANTON
END
