
CREATE procedure [dbo].[PA_ELIMINAR_TIPO_MAQUINA]
	@ID_TIPO_MAQUINA INT
AS
BEGIN
	DELETE TIPO_MAQUINA WHERE ID_TIPO_MAQUINA=@ID_TIPO_MAQUINA
END

CREATE procedure [dbo].[PA_ELIMINAR_TIPO_MAQUINA]
	@ID_TIPO_MAQUINA INT
AS
BEGIN
	DELETE TIPO_MAQUINA WHERE ID_TIPO_MAQUINA=@ID_TIPO_MAQUINA
END

CREATE procedure dbo.PA_ELIMINAR_TIPO_MAQUINA
	@ID_TIPO_MAQUINA INT
AS
BEGIN
	DELETE TIPO_MAQUINA WHERE ID_TIPO_MAQUINA=@ID_TIPO_MAQUINA
END
