

CREATE procedure [dbo].[PA_ELIMINAR_PROVINCIA]
	@ID_PROVINCIA INT
AS
BEGIN
	DELETE PROVINCIA WHERE id_Provincia=@ID_PROVINCIA
END

CREATE procedure [dbo].[PA_ELIMINAR_PROVINCIA]
	@ID_PROVINCIA INT
AS
BEGIN
	DELETE PROVINCIA WHERE id_Provincia=@ID_PROVINCIA
END

CREATE procedure dbo.PA_ELIMINAR_PROVINCIA
	@ID_PROVINCIA INT
AS
BEGIN
	DELETE PROVINCIA WHERE id_Provincia=@ID_PROVINCIA
END
