
Create procedure [dbo].[PA_ELIMINAR_TIPO_EJERCICIO]
	@ID_TIPO_EJERCICIO INT
AS
BEGIN
	DELETE TIPO_EJERCICIO WHERE ID_TIPO_EJERCICIO=@ID_TIPO_EJERCICIO
END

Create procedure [dbo].[PA_ELIMINAR_TIPO_EJERCICIO]
	@ID_TIPO_EJERCICIO INT
AS
BEGIN
	DELETE TIPO_EJERCICIO WHERE ID_TIPO_EJERCICIO=@ID_TIPO_EJERCICIO
END

Create procedure dbo.PA_ELIMINAR_TIPO_EJERCICIO
	@ID_TIPO_EJERCICIO INT
AS
BEGIN
	DELETE TIPO_EJERCICIO WHERE ID_TIPO_EJERCICIO=@ID_TIPO_EJERCICIO
END
