
CREATE procedure [dbo].[PA_ELIMINAR_DISTRITO]
	@ID_DISTRITO INT
AS
BEGIN
	DELETE Distrito WHERE id_Distrito=@ID_DISTRITO
END

CREATE procedure [dbo].[PA_ELIMINAR_DISTRITO]
	@ID_DISTRITO INT
AS
BEGIN
	DELETE Distrito WHERE id_Distrito=@ID_DISTRITO
END

CREATE procedure dbo.PA_ELIMINAR_DISTRITO
	@ID_DISTRITO INT
AS
BEGIN
	DELETE Distrito WHERE id_Distrito=@ID_DISTRITO
END
