Create procedure PA_ELIMINAR_TIPO_USUARIO
    @ID_TIPO_USUARIO INT

AS
BEGIN

    DELETE FROM TIPO_USUARIO WHERE ID_TIPO_USUARIO=@ID_TIPO_USUARIO

END

Create procedure [dbo].[PA_ELIMINAR_TIPO_USUARIO]
    @ID_TIPO_USUARIO INT

AS
BEGIN

    DELETE FROM TIPO_USUARIO WHERE ID_TIPO_USUARIO=@ID_TIPO_USUARIO

END

Create procedure dbo.PA_ELIMINAR_TIPO_USUARIO
    @ID_TIPO_USUARIO INT

AS
BEGIN

    DELETE FROM TIPO_USUARIO WHERE ID_TIPO_USUARIO=@ID_TIPO_USUARIO

END
