
CREATE PROCEDURE INSERTAR_NUEVA_RUTINA

	@FECHA_INICIO_RUTINA VARCHAR(255),
	@FECHA_FIN_RUTINA VARCHAR(255),
	@OBJETIVOS VARCHAR(800),
	@NUMERO_DE_REPETICIONES VARCHAR(255),
	@NUMERO_DE_DESCANSOS VARCHAR(255),
	@CUELLO VARCHAR(255),
	@HOMBROS VARCHAR(255),
	@PECHO VARCHAR(255),
	@ESPALDA VARCHAR(255),
	@ABDOMEN VARCHAR(255),
	@ANTEBRAZOS VARCHAR(255),
	@PIERNA VARCHAR(255),
	@PANTORRILLAS VARCHAR(255),
	@BICEPS VARCHAR(255),
	@TRICEPS VARCHAR(255),
	@OBLICUOS VARCHAR(255),
	@FK_TIPO_MAQUINA INT ,
	@FK_TIPO_EJERCICIO INT,
	@FK_USUARIO_INSTRUCTOR INT,
	@FK_USUARIO_JUGADOR INT

AS
BEGIN

	INSERT INTO INSERTAR_NUEVA_RUTINA
	VALUES(

			@FECHA_INICIO_RUTINA,
			@FECHA_FIN_RUTINA,
			@OBJETIVOS,
			@NUMERO_DE_REPETICIONES,
			@NUMERO_DE_DESCANSOS,
			@CUELLO,
			@HOMBROS,
			@PECHO,
			@ESPALDA,
			@ABDOMEN,
			@ANTEBRAZOS,
			@PIERNA,
			@PANTORRILLAS,
			@BICEPS,
			@TRICEPS,
			@OBLICUOS,
			@FK_TIPO_MAQUINA,
			@FK_TIPO_EJERCICIO,
			@FK_USUARIO_INSTRUCTOR,
			@FK_USUARIO_JUGADOR

	)
END

CREATE PROCEDURE [dbo].[PA_INSERTAR_NUEVA_RUTINA]

	@FECHA_INICIO_RUTINA VARCHAR(255),
	@FECHA_FIN_RUTINA VARCHAR(255),
	@OBJETIVOS VARCHAR(800),
	@NUMERO_DE_REPETICIONES VARCHAR(255),
	@NUMERO_DE_DESCANSOS VARCHAR(255),
	@CUELLO VARCHAR(255),
	@HOMBROS VARCHAR(255),
	@PECHO VARCHAR(255),
	@ESPALDA VARCHAR(255),
	@ABDOMEN VARCHAR(255),
	@ANTEBRAZOS VARCHAR(255),
	@PIERNA VARCHAR(255),
	@PANTORRILLAS VARCHAR(255),
	@BICEPS VARCHAR(255),
	@TRICEPS VARCHAR(255),
	@OBLICUOS VARCHAR(255),
	@FK_TIPO_MAQUINA INT ,
	@FK_TIPO_EJERCICIO INT,
	@FK_USUARIO_INSTRUCTOR INT,
	@FK_USUARIO_JUGADOR INT

AS
BEGIN

	INSERT INTO INSERTAR_NUEVA_RUTINA
	VALUES(

			@FECHA_INICIO_RUTINA,
			@FECHA_FIN_RUTINA,
			@OBJETIVOS,
			@NUMERO_DE_REPETICIONES,
			@NUMERO_DE_DESCANSOS,
			@CUELLO,
			@HOMBROS,
			@PECHO,
			@ESPALDA,
			@ABDOMEN,
			@ANTEBRAZOS,
			@PIERNA,
			@PANTORRILLAS,
			@BICEPS,
			@TRICEPS,
			@OBLICUOS,
			@FK_TIPO_MAQUINA,
			@FK_TIPO_EJERCICIO,
			@FK_USUARIO_INSTRUCTOR,
			@FK_USUARIO_JUGADOR

	)
END

CREATE PROCEDURE PA_INSERTAR_NUEVARUTINA

	@Usuario_Instructor INT,
	@Usuario_Jugador INT,
	@Fecha_Inicio_Rutina VARCHAR(255),
	@Fecha_Fin_Rutina VARCHAR(255),
	@Objetivos VARCHAR(800),
	@Numero_de_Repeticiones VARCHAR(255),
	@Numero_de_Descansos VARCHAR(255),
	@Espalda VARCHAR(255),
	@Hombros VARCHAR(255),
	@Pecho VARCHAR(255),
	@Abdomen VARCHAR(255),
	@Antebrazos VARCHAR(255),
	@Cuadriceps VARCHAR(255),
	@Pantorrillas VARCHAR(255),
	@Biceps VARCHAR(255),
	@Triceps  VARCHAR(255),
	@Oblicuos VARCHAR(255),
	@FK_TIPO_MAQUINA INT,
	@FK_TIPO_EJERCICIO INT


AS
BEGIN

	INSERT INTO NuevaRutina
	VALUES(@Usuario_Instructor, @Usuario_Jugador,
			@Fecha_Inicio_Rutina, @Fecha_Fin_Rutina, @Objetivos, @Numero_de_Repeticiones, @Numero_de_Descansos,
			@Espalda, @Hombros, @Pecho, @Abdomen, @Antebrazos, @Cuadriceps, @Pantorrillas, @Biceps,
			@Triceps, @Oblicuos, @FK_TIPO_MAQUINA, @FK_TIPO_EJERCICIO)

END
GO

CREATE PROCEDURE dbo.PA_INSERTAR_NUEVA_RUTINA

	@FECHA_INICIO_RUTINA VARCHAR(255),
	@FECHA_FIN_RUTINA VARCHAR(255),
	@OBJETIVOS VARCHAR(800),
	@NUMERO_DE_REPETICIONES VARCHAR(255),
	@NUMERO_DE_DESCANSOS VARCHAR(255),
	@CUELLO VARCHAR(255),
	@HOMBROS VARCHAR(255),
	@PECHO VARCHAR(255),
	@ESPALDA VARCHAR(255),
	@ABDOMEN VARCHAR(255),
	@ANTEBRAZOS VARCHAR(255),
	@PIERNA VARCHAR(255),
	@PANTORRILLAS VARCHAR(255),
	@BICEPS VARCHAR(255),
	@TRICEPS VARCHAR(255),
	@OBLICUOS VARCHAR(255),
	@FK_TIPO_MAQUINA INT ,
	@FK_TIPO_EJERCICIO INT,
	@FK_USUARIO_INSTRUCTOR INT,
	@FK_USUARIO_JUGADOR INT

AS
BEGIN

	INSERT INTO INSERTAR_NUEVA_RUTINA
	VALUES(

			@FECHA_INICIO_RUTINA,
			@FECHA_FIN_RUTINA,
			@OBJETIVOS,
			@NUMERO_DE_REPETICIONES,
			@NUMERO_DE_DESCANSOS,
			@CUELLO,
			@HOMBROS,
			@PECHO,
			@ESPALDA,
			@ABDOMEN,
			@ANTEBRAZOS,
			@PIERNA,
			@PANTORRILLAS,
			@BICEPS,
			@TRICEPS,
			@OBLICUOS,
			@FK_TIPO_MAQUINA,
			@FK_TIPO_EJERCICIO,
			@FK_USUARIO_INSTRUCTOR,
			@FK_USUARIO_JUGADOR

	)
END

CREATE PROCEDURE PA_INSERTAR_NUEVA_RUTINA

	@id_Rutina INT,
	@Usuario_Instructor INT,
	@Usuario_Jugador INT,
	@FE_Inicio_Rutina VARCHAR(255),
	@FE_Fin_Rutina VARCHAR(255),
	@Objetivos VARCHAR(800),
	@Numero_de_Repeticiones VARCHAR(255),
	@Numero_de_Descansos VARCHAR(255),
	@Espalda VARCHAR(255),
	@Hombros VARCHAR(255),
	@Pecho VARCHAR(255),
	@Abdomen VARCHAR(255),
	@Antebrazos VARCHAR(255),
	@Cuadriceps VARCHAR(255),
	@Pantorrillas VARCHAR(255),
	@Biceps VARCHAR(255),
	@Triceps  VARCHAR(255),
	@Oblicuos VARCHAR(255)

AS
BEGIN

	INSERT INTO NUEVA_RUTINA
	VALUES(@id_Rutina, @Usuario_Instructor, @Usuario_Jugador,
			@FE_Inicio_Rutina, @FE_Fin_Rutina, @Objetivos, @Numero_de_Repeticiones, @Numero_de_Descansos,
			@Espalda, @Hombros, @Pecho, @Abdomen, @Antebrazos, @Cuadriceps, @Pantorrillas, @Biceps,
			@Triceps, @Oblicuos

END
