USE [Gimnacio]
GO
/****** Object:  StoredProcedure [dbo].[PA_RETORNA_JUGADOR]    Script Date: 5/3/2019 22:29:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PA_RETORNA_JUGADOR]
@ID_JUGADOR INT
AS
BEGIN 


SELECT JUG.ID_JUGADOR,JUG.CORREO,JUG.CEDULA,JUG.NOMBRE,JUG.PRIMERAPELLIDO,JUG.SEGUNDOAPELLIDO,JUG.FECHA_DEBUT,JUG.PROVINCIA,
JUG.CANTON,JUG.DISTRITO,JUG.FOTO,JUG.FECHA_DE_INGRESO,JUG.FECHA_DE_INSERCION,JUG.FECHA_DE_MODIFICACION,JUG.USUARIO_MODIFICACION  
FROM Jugadores  AS JUG
WHERE id_Jugador=@ID_JUGADOR

END 