USE [GimnacioBD]
GO
/****** Object:  StoredProcedure [dbo].[PA_RETORNA_CLIENTES]    Script Date: 12/03/2020 21:42:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PA_RETORNA_CANTON]
    @ID_CANTON INT
AS
BEGIN


    SELECT CANT.ID_CANTON, CANT.ID_PROVINCIA, CANT.NOMBRE, CANT.USUARIO_CREA, CANT.FECHA_CREACION, CANT.usuario_modifcacion, CANT.FECHA_MODIFICACION, CANT.VC_ESTADO
    FROM CANTON AS CANT
    WHERE id_Canton=@ID_CANTON

END

CREATE PROCEDURE [dbo].[PA_RETORNA_CANTON]
    @ID_CANTON INT
AS
BEGIN


    SELECT CANT.ID_CANTON, CANT.ID_PROVINCIA, CANT.NOMBRE, CANT.USUARIO_CREA, CANT.FECHA_CREACION, CANT.usuario_modifcacion, CANT.FECHA_MODIFICACION, CANT.VC_ESTADO
    FROM CANTON AS CANT
    WHERE id_Canton=@ID_CANTON

END
