USE [GimnacioBD]
GO
/****** Object:  StoredProcedure [dbo].[PA_RETORNA_CANTON]    Script Date: 14/03/2020 14:18:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PA_RETORNA_PROVINCIA]
    @ID_PROVINCIA INT
AS
BEGIN


    SELECT PROV.ID_PROVINCIA, PROV.NOMBRE, PROV.USUARIO_CREA, PROV.FECHA_CREA, PROV.USUARIO_MODIFICA, PROV.FECHA_MODIFICA, PROV.VC_ESTADO
    FROM PROVINCIA AS PROV
    WHERE id_Provincia=@ID_PROVINCIA

END

CREATE PROCEDURE [dbo].[PA_RETORNA_PROVINCIA]
    @ID_PROVINCIA INT
AS
BEGIN


    SELECT PROV.ID_PROVINCIA, PROV.NOMBRE, PROV.USUARIO_CREA, PROV.FECHA_CREA, PROV.USUARIO_MODIFICA, PROV.FECHA_MODIFICA, PROV.VC_ESTADO
    FROM PROVINCIA AS PROV
    WHERE id_Provincia=@ID_PROVINCIA
